version: "1"
services:
  server:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: "mysql:8.0-debian"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 135246
      MYSQL_DATABASE: jjour